global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s
    honor_labels: true

  - job_name: 'xgboost_training'
    static_configs:
      - targets: ['pushgateway:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s
    params:
      job: ['xgboost_training']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
